[Function][Vectorized] Implement random/rand vectorized function
doris-vectorized/doris-vectorized pull request #186
Opened 2021-09-28 07:09 UTC by xinghuayu007

## Proposed changes

Implement random/rand vectorized function.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-09-28 11:36 UTC, BiteTheDDDDt requested changes

2021-09-28 11:36 UTC, BiteTheDDDDt commented on be/src/vec/functions/random.h
> +            std::mt19937 generator(std::random_device{}());
```suggestion
            std::mt19937_64 generator(std::random_device{}());
```

2021-09-29 04:20 UTC, xinghuayu007 commented on be/src/vec/functions/random.h
> +            std::mt19937 generator(std::random_device{}());
done

2021-09-29 11:16 UTC, zhangstar333 commented on be/src/vec/functions/random.h
> +
无参数时，过不了，可以加上这句
bool is_variadic() const override { return true; }

2021-09-29 11:25 UTC, xinghuayu007 commented on be/src/vec/functions/random.h
> +
无参数场景，我测试过，是可以的

2021-09-29 11:32 UTC, zhangstar333 commented on be/src/vec/functions/random.h
> +
在开向量化下吗？

2021-09-29 11:33 UTC, xinghuayu007 commented on be/src/vec/functions/random.h
> +
对

2021-09-29 12:04 UTC, zhangstar333 commented on be/src/vec/functions/random.h
> +
刚试了下,Debug模式会core，Release下没有问题，但是不知道为啥无参数时返回Empty Set

2021-09-30 01:04 UTC, xinghuayu007 commented on be/src/vec/functions/random.h
> +
![2021-09-30 09-02-53屏幕截图](https://user-images.githubusercontent.com/12771191/135368864-381a22b8-0f01-435b-bccb-3797e1ef009c.png)

2021-09-30 02:59 UTC, HappenLee commented on be/src/vec/functions/random.h
> +
辛苦补充一下ut，在确定种子的值时候

2021-10-21 08:51 UTC, HappenLee commented on be/src/vec/functions/random.h
> +    bool use_default_implementation_for_nulls() const override { return false; }
为什么不用默认的null实现，rand(null)应该返回null吧

2021-12-09 09:43 UTC, closed without merging